import Footer from "./components/layout/Footer";
import Nav from "./components/layout/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import Input from "./components/inputs/Input";
import { SessionProvider } from "next-auth/react";
import { NextAuthProvider } from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <NextAuthProvider>
          <Nav />

          {children}
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
